[package]
name = "epost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = { path = "../egg" }

thiserror = "1"
clap = { version = "4", features = ["cargo"] }

[dev-dependencies]
anyhow = "1"

